name: 'Semantic Release'
description: 'Semantic Release workflow with npm, git, pnpm, and pre-release scripts'
inputs:
  GITHUB_TOKEN:  # GitHub PAT
    description: 'GitHub Personal Access Token'
    required: false
  NPM_TOKEN:  # NPM Token
    description: 'NPM Token'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ inputs.GITHUB_TOKEN }}

    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
        cache: pnpm

    - name: Run release script
      env:
        GITHUB_TOKEN: ${{ github.token }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      run: ${{ github.action_path }}/release.sh
      shell: bash
